//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Config.Tables
{ 
    public enum EAttributeType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 生命
        /// </summary>
        Health = 1,
        /// <summary>
        /// 最大生命
        /// </summary>
        MaxHealth = 2,
        /// <summary>
        /// 攻击
        /// </summary>
        Attack = 3,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 4,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalRate = 5,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CriticalDamage = 6,
    }

} 
