//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Config.Tables
{ 
    public enum EBuffType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 回合结束时回复X点生命
        /// </summary>
        Regeneration = 10001,
        /// <summary>
        /// 受到伤害减少X%
        /// </summary>
        Perseverance = 10002,
        /// <summary>
        /// 攻击伤害提升X%
        /// </summary>
        PowerSurge = 10003,
        /// <summary>
        /// 受到伤害增加X%
        /// </summary>
        Vulnerable = 20001,
        /// <summary>
        /// 造成伤害降低X%
        /// </summary>
        Weak = 20002,
        /// <summary>
        /// 无法行动
        /// </summary>
        Stunned = 20003,
        /// <summary>
        /// 回合结束时受到X点伤害
        /// </summary>
        Bleed = 20004,
    }

} 
