//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Game.Config.Tables
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 1,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 2,
    }

} 
