//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Config.Tables
{
public sealed partial class GlobalConfig :  Bright.Config.BeanBase 
{
    public GlobalConfig(ByteBuf _buf) 
    {
        DefaultPlayerCharacter = _buf.ReadString();
        PostInit();
    }

    public static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new GlobalConfig(_buf);
    }

    /// <summary>
    /// 默认玩家角色id
    /// </summary>
    public string DefaultPlayerCharacter { get; private set; }

    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DefaultPlayerCharacter:" + DefaultPlayerCharacter + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}