//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Config.Tables
{
public sealed partial class Reward :  Bright.Config.BeanBase 
{
    public Reward(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        Count = _buf.ReadInt();
        Description = _buf.ReadString();
        PostInit();
    }

    public static Reward DeserializeReward(ByteBuf _buf)
    {
        return new Reward(_buf);
    }

    /// <summary>
    /// 这是Id
    /// </summary>
    public int ItemId { get; private set; }
    /// <summary>
    /// 数量
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Description { get; private set; }

    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "Count:" + Count + ","
        + "Description:" + Description + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}