//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Config.Tables
{
   
public partial class TbAbilityConfig
{
    private readonly Dictionary<string, AbilityConfig> _dataMap;
    private readonly List<AbilityConfig> _dataList;
    
    public TbAbilityConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, AbilityConfig>();
        _dataList = new List<AbilityConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AbilityConfig _v;
            _v = AbilityConfig.DeserializeAbilityConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, AbilityConfig> DataMap => _dataMap;
    public List<AbilityConfig> DataList => _dataList;

    public AbilityConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AbilityConfig Get(string key) => _dataMap[key];
    public AbilityConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}