
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 
    /// <summary>
    /// 装备类型
    /// </summary>
    public enum EEquipmentType
    {
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 0,
        /// <summary>
        /// 防具
        /// </summary>
        Armor = 1,
        /// <summary>
        /// 饰品
        /// </summary>
        Jewelry = 2,
    }

 

