
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class EquipmentConfig : Luban.BeanBase
{
    public EquipmentConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NameTextId = _buf.ReadInt();
        Level = _buf.ReadInt();
        Price = _buf.ReadFloat();
        Type = (EEquipmentType)_buf.ReadInt();
        DescriptionTextId = _buf.ReadInt();
    }

    public static EquipmentConfig DeserializeEquipmentConfig(ByteBuf _buf)
    {
        return new EquipmentConfig(_buf);
    }

    /// <summary>
    /// 这是Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称文本Id
    /// </summary>
    public readonly int NameTextId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly EEquipmentType Type;
    /// <summary>
    /// 描述文本Id
    /// </summary>
    public readonly int DescriptionTextId;
   
    public const int __ID__ = -824956336;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameTextId:" + NameTextId + ","
        + "level:" + Level + ","
        + "price:" + Price + ","
        + "type:" + Type + ","
        + "descriptionTextId:" + DescriptionTextId + ","
        + "}";
    }
}



