
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class LocalizationConfig : Luban.BeanBase
{
    public LocalizationConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ZhHans = _buf.ReadString();
        ZhHant = _buf.ReadString();
        En = _buf.ReadString();
    }

    public static LocalizationConfig DeserializeLocalizationConfig(ByteBuf _buf)
    {
        return new LocalizationConfig(_buf);
    }

    /// <summary>
    /// 这是Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文简体
    /// </summary>
    public readonly string ZhHans;
    /// <summary>
    /// 中文繁體
    /// </summary>
    public readonly string ZhHant;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = -1901143205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "zhHans:" + ZhHans + ","
        + "zhHant:" + ZhHant + ","
        + "en:" + En + ","
        + "}";
    }
}



