
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class Reward : Luban.BeanBase
{
    public Reward(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        Count = _buf.ReadInt();
        Description = _buf.ReadString();
    }

    public static Reward DeserializeReward(ByteBuf _buf)
    {
        return new Reward(_buf);
    }

    /// <summary>
    /// 这是Id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "description:" + Description + ","
        + "}";
    }
}



