
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


public partial class Tables
{
    public Examples.TbExampleBasic TbExampleBasic {get; }
    public Examples.TbExampleAdvance TbExampleAdvance {get; }
    public Examples.TbExampleSingleton TbExampleSingleton {get; }
    public Examples.TbExampleList TbExampleList {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbExampleBasic = new Examples.TbExampleBasic(loader("examples_tbexamplebasic"));
        TbExampleAdvance = new Examples.TbExampleAdvance(loader("examples_tbexampleadvance"));
        TbExampleSingleton = new Examples.TbExampleSingleton(loader("examples_tbexamplesingleton"));
        TbExampleList = new Examples.TbExampleList(loader("examples_tbexamplelist"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbExampleBasic.ResolveRef(this);
        TbExampleAdvance.ResolveRef(this);
        TbExampleSingleton.ResolveRef(this);
        TbExampleList.ResolveRef(this);
    }
}


