
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class TbEquipmentConfig
{
    private readonly System.Collections.Generic.Dictionary<int, EquipmentConfig> _dataMap;
    private readonly System.Collections.Generic.List<EquipmentConfig> _dataList;
    
    public TbEquipmentConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EquipmentConfig>();
        _dataList = new System.Collections.Generic.List<EquipmentConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EquipmentConfig _v;
            _v = EquipmentConfig.DeserializeEquipmentConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EquipmentConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EquipmentConfig> DataList => _dataList;

    public EquipmentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EquipmentConfig Get(int key) => _dataMap[key];
    public EquipmentConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



