//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Config.Tables.Examples
{
   
public partial class TbExampleAdvance
{
    private readonly List<Examples.ExampleAdvance> _dataList;


    public TbExampleAdvance(ByteBuf _buf)
    {
        _dataList = new List<Examples.ExampleAdvance>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Examples.ExampleAdvance _v;
            _v = Examples.ExampleAdvance.DeserializeExampleAdvance(_buf);
            _dataList.Add(_v);
        }
        PostInit();
    }


    public List<Examples.ExampleAdvance> DataList => _dataList;


    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}