//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Game.Config.Tables.Examples
{
   
public partial class TbExampleBasic
{
    private readonly Dictionary<int, Examples.ExampleBasic> _dataMap;
    private readonly List<Examples.ExampleBasic> _dataList;
    
    public TbExampleBasic(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Examples.ExampleBasic>();
        _dataList = new List<Examples.ExampleBasic>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Examples.ExampleBasic _v;
            _v = Examples.ExampleBasic.DeserializeExampleBasic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Examples.ExampleBasic> DataMap => _dataMap;
    public List<Examples.ExampleBasic> DataList => _dataList;

    public Examples.ExampleBasic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Examples.ExampleBasic Get(int key) => _dataMap[key];
    public Examples.ExampleBasic this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}