
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Examples
{
public sealed partial class ListConfig : Luban.BeanBase
{
    public ListConfig(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
        Race = _buf.ReadString();
        Occupation = _buf.ReadString();
        Age = _buf.ReadInt();
        Origin = _buf.ReadString();
    }

    public static ListConfig DeserializeListConfig(ByteBuf _buf)
    {
        return new Examples.ListConfig(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 种族
    /// </summary>
    public readonly string Race;
    /// <summary>
    /// 职业
    /// </summary>
    public readonly string Occupation;
    /// <summary>
    /// 年龄
    /// </summary>
    public readonly int Age;
    /// <summary>
    /// 出身地
    /// </summary>
    public readonly string Origin;
   
    public const int __ID__ = -1997864891;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "race:" + Race + ","
        + "occupation:" + Occupation + ","
        + "age:" + Age + ","
        + "origin:" + Origin + ","
        + "}";
    }
}

}

