
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Examples
{
public partial class TbBasicConfig
{
    private readonly System.Collections.Generic.Dictionary<int, Examples.BasicConfig> _dataMap;
    private readonly System.Collections.Generic.List<Examples.BasicConfig> _dataList;
    
    public TbBasicConfig(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Examples.BasicConfig>();
        _dataList = new System.Collections.Generic.List<Examples.BasicConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Examples.BasicConfig _v;
            _v = Examples.BasicConfig.DeserializeBasicConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Examples.BasicConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Examples.BasicConfig> DataList => _dataList;

    public Examples.BasicConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Examples.BasicConfig Get(int key) => _dataMap[key];
    public Examples.BasicConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

